// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeYcO0c4caAIS2Ml7lHwAQUhXxZZy47lY',
    appId: '1:1098009660493:web:295096ea3c6174df6e2004',
    messagingSenderId: '1098009660493',
    projectId: 'budgetbuddy-2f7aa',
    authDomain: 'budgetbuddy-2f7aa.firebaseapp.com',
    storageBucket: 'budgetbuddy-2f7aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ8s__bHMAKZxiQ2-NsIdfD_Nkjdap_PE',
    appId: '1:1098009660493:android:0b9ef7138174b6966e2004',
    messagingSenderId: '1098009660493',
    projectId: 'budgetbuddy-2f7aa',
    storageBucket: 'budgetbuddy-2f7aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS4pyFPSYj38VIFfMCsYCyCkJQCxi20NE',
    appId: '1:1098009660493:ios:8e32e472cc71d6e26e2004',
    messagingSenderId: '1098009660493',
    projectId: 'budgetbuddy-2f7aa',
    storageBucket: 'budgetbuddy-2f7aa.firebasestorage.app',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS4pyFPSYj38VIFfMCsYCyCkJQCxi20NE',
    appId: '1:1098009660493:ios:8e32e472cc71d6e26e2004',
    messagingSenderId: '1098009660493',
    projectId: 'budgetbuddy-2f7aa',
    storageBucket: 'budgetbuddy-2f7aa.firebasestorage.app',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeYcO0c4caAIS2Ml7lHwAQUhXxZZy47lY',
    appId: '1:1098009660493:web:670dada1a56d1f6f6e2004',
    messagingSenderId: '1098009660493',
    projectId: 'budgetbuddy-2f7aa',
    authDomain: 'budgetbuddy-2f7aa.firebaseapp.com',
    storageBucket: 'budgetbuddy-2f7aa.firebasestorage.app',
  );

}